### ISSUE TITLE
Redirect process output directly to screen instead of waiting for line endings?

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#196] opened 2015-04-21 14:25 UTC
Currently `runAsync` buffers the output until encountering a line ending, and then passes it to `log`.  `log` currently just forwards to `print`, but we will likely want to change that in the future.  Some potential changes:

* #100
* https://github.com/google/grinder.dart/issues/170#issuecomment-93050805
* https://github.com/google/grinder.dart/issues/101#issuecomment-94081290.  

However, some apps use ansi escape sequences to do clever UI enhancements, such as a progress animation, or not actually printing out newlines, but rather replacing the line output once a new line occurs, such as `test` (see #194).  But when grinder calls these processes they will likely eventually (https://dartbug.com/21821) see the `stdioType` as a pipe, and disable these features anyways.  Unless dart will provide some way for a child process to inherit the stdio (`stdioType` especially) of a parent process (grinder in this case)?

So should `runAsync` (and it's callers) have a mode which enables these interactive features, and doesn't buffer the output for later consumption by `log`?  Should it be the default?

**Comment by devoncarew** [comment] 2015-12-14 06:29
dupe of #290

**Closed by devoncarew** 2015-12-14 06:29 UTC
Labels: question
