### ISSUE TITLE
Support for running tasks in parallel

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#261] opened 2015-05-30 03:06 UTC
Does grinder have a parallel task support? If not, would it make sense to add it?

I'd like to speed up my tasks. If some of them can be run in parallel, that would be great if grinder could help make that easier.

Thanks for considering!

**Comment by zoechi** [comment] 2015-05-30 08:29
Are you talking about `runAsync` which would run external processes in parallel or about running Dart tasks in parallel (isolates). 
Support for Running Grinder tasks in Isolates while still using sync inside tasks would be quit nice.

**Comment by sethladd** [comment] 2015-05-30 12:25
I probably mean isolates. :)

**Comment by zoechi** [comment] 2015-05-30 12:44
or both ;-) `@DependsParallel(task1, task2,...)`?

**Comment by sethladd** [comment] 2015-06-01 03:06
Something like that, yeah. I want to spin up a bunch of independent tasks,
and when they all complete, move on.

**Comment by seaneagan** [comment] 2015-06-02 13:57
dupe of #170

**Closed by seaneagan** 2015-06-02 13:57 UTC
Labels: enhancement
