### ISSUE TITLE
grinder doesn't wait for async tasks to finish

### ISSUE THREAD

**Issue by devoncarew** [google/grinder.dart#273] opened 2015-06-18 14:01 UTC
```dart
@Task('Analyze the source code with the ddc compiler')
ddc() {
  PubApp ddc = new PubApp.global('dev_compiler');
  return ddc.runAsync(['web/entry.dart'], script: 'devc');
}
```

For this example, the task returns a future, but the `finished` text is printed out immediately after the task is called (before it finishes).

```
grinder running [ddc]

[ddc]
  pub global run dev_compiler:devc web/entry.dart

finished in 0.741 seconds.
  severe: line 143, column 33 of package:atom_dart/impl/analysis_server_impl.dart: [StaticTypeError] Type check failed: ne
    w LineSplitter() (LineSplitter) is not of type StreamTransformer<String, dynamic>
      _process.onStdout.transform(new LineSplitter()).listen((String line) {
                                  ^^^^^^^^^^^^^^^^^^
```

**Comment by seaneagan** [comment] 2015-07-06 19:28
Just looked into this, and we have many APIs that return Futures, but aren't wrapped in APIs, such as `new Future(...)` that guarantee that they return a Future, e.g. `executeTask`, `Grinder.start` and `runAsync`.  Not sure if that's what's causing this issue or not, but it needs to be fixed.  There are two options for fixing that:

1. Use async-await, which requires an sdk constraint of >=1.9.0, which is a breaking change, and so needs to wait for grinder version 0.8.0.
1. Wrap the APIs in `=> new Future(() {/* code here */});` in 0.7.x and move to async-await later.

@devoncarew which do you prefer?

**Comment by devoncarew** [comment] 2015-07-07 02:54
From tracing the path through some of those calls, I don't see where we're not returning a `Future` properly. Perhaps the issue's in task execution? I'll need to run through this in the debugger -

**Comment by devoncarew** [comment] 2015-07-08 21:58
I can't get a repo case for this now.

**Comment by seaneagan** [comment] 2015-07-08 23:05
I think this is a dupe of #265.

**Closed** 2015-10-23 04:48 UTC
Labels: P1
